### ISSUE TITLE
Errors building in Xcode 6.3

### ISSUE THREAD

**Issue by imavca** [MengTo/DesignerNewsApp#101]
After cloning and updating the submodules, I build the target "DesignerNewsApp" in Xcode 6.3 and got several errors.

**Comment by schneiderandre** [comment]
I'll take a look!

**Comment by a11enwong** [comment]
Wish to fix it ASAP.

**Comment by schneiderandre** [comment]
I migrated to Xcode 6.3 in #102, which is merged now.
