### ISSUE TITLE
WatchKit Main Interace Controller

### ISSUE THREAD

**Issue by schneiderandre** [MengTo/DesignerNewsApp#113]
Currently we are using a simple page-based navigation to switch between top and recent Stories:
![bildschirmfoto 2015-07-13 um 14 58 43](https://cloud.githubusercontent.com/assets/975938/8651234/03fe6f42-2978-11e5-861c-fdfba971a9b1.png)

I wonder if we should convert this to a hierarchical Interface, similar to Twitters Watch App?

![bildschirmfoto 2015-07-13 um 16 02 14](https://cloud.githubusercontent.com/assets/975938/8651364/966b99d6-2978-11e5-9c8a-409cf46b4b70.png)

**Comment by MengTo** [comment]
I think the second screen is not necessary since we can just swipe to switch. Go to Top stories directly.

**Comment by schneiderandre** [comment]
You're right. :+1:
