### ISSUE TITLE
Copyright Claim?

### ISSUE THREAD

**Issue by winkelsdorf** [MengTo/DesignerNewsApp#123]
Hi there,

nice demo! 

Speaking of what's usual with OpenSource development, I am wondering if you had been working together with André Schneider https://github.com/schneiderandre on this project? As I saw the Demo I saw the similarity of some effects, they look like they were taken from André's Popping Library (https://github.com/schneiderandre/popping).

You mention him as a developer in the sources, that's good:
https://github.com/MengTo/DesignerNewsApp/search?utf8=✓&q=André+Schneider

But it's copyrighted now to Meng To? That's why I ask..
```
//  Created by André Schneider on 16.03.15.
//  Copyright (c) 2015 Meng To. All rights reserved.
```
As far as I can see he licenses his sources under MIT license, probably best to include it for those externals. If you'd been working on this together, just ignore this post :)

Cheers,
Frederik

**Comment by MengTo** [comment]
Thanks for taking the time to write this. Yes, Andre and I are part of the same team on this project. :)

**Comment by winkelsdorf** [comment]
You're welcome. Good to hear that :) Closing this, as it's way obsolete now. Keep up your work!
