### ISSUE TITLE
Git submodule Error

### ISSUE THREAD

**Issue by joshuasoehn** [MengTo/DesignerNewsApp#88]
Cloned the repository but running "git submodule update --init --recursive" can't clone into DTCoreText

```
Cloning into 'Externals/DTCoreText'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by MengTo** [comment]
Hmm I'm also getting this error. @jamztang, what do you think?

**Comment by jamztang** [comment]
For me I can never experience the issue because I suspect my account is the owner of those dependancies. I currently made a patch to point back to the original repo. Let me know if it works for you guys.

Please remove the old one and follow the instructions over. Cheers!

**Comment by MengTo** [comment]
Works perfectly this time, no more permission problems! Great job @jamztang !

**Comment by jamztang** [comment]
Awesome!

**Comment by joshuasoehn** [comment]
Thanks guys <3
