### ISSUE TITLE
Can't run app in Xcode 6.2

### ISSUE THREAD

**Issue by naartjie** [MengTo/DesignerNewsApp#95]
I just tried installing and running in Xcode 6.2.

After updating git submodules, I opened Xcode, and tried to run in a simulator, but I am getting the following error about Alamofilre:
![screen shot 2015-03-16 at 13 45 07](https://cloud.githubusercontent.com/assets/514563/6674978/182574b8-cbe3-11e4-9064-50b284155b62.png)

**Comment by naartjie** [comment]
Nevermind, it's working now. I opened it in Xcode 6.3 beta first, and a clean afterwards didn't seem to fix it, but it worked after doing a clean checkout, and opening it in Xcode 6.2 from fresh.

**Comment by schneiderandre** [comment]
That was fast! :+1:
