### ISSUE TITLE
Feature: Watch App for sending best stories with over 30 upvotes

### ISSUE THREAD

**Issue by MengTo** [MengTo/DesignerNewsApp#98]
This is an experimental feature that would notify Watch users about top news with over X number of upvotes.

**Comment by schneiderandre** [comment]
Is there still interest in this feature? If yes, should we use watchOS2?

**Comment by schneiderandre** [comment]
Current progress:

I moved the reusable Parts of the App in a Framework, so they can be used in the WatchKit Extension and the Application itself.

- Page based Navigation for top and recent stories, which includes
 - title
 - badge image (if available)
 - author name
 - comment count
 - upvote count

- Modal View For upvoting a Story
 - badige image
 - author
 - title
 - upvote button

@MengTo Both views look nearly identical and I would like to get some feedback and design details before moving on. There is definitely space to improve the current design and provide a better UX :+1: 
As discussed in #109 I would use the v2 API for a solid way to upvote from the Watch and keep everything in sync.

<img width="424" alt="bildschirmfoto 2015-07-11 um 16 46 10" src="https://cloud.githubusercontent.com/assets/975938/8634130/69d413a4-27ec-11e5-82b4-b6400b922fc0.png">
<img width="424" alt="bildschirmfoto 2015-07-11 um 16 46 15" src="https://cloud.githubusercontent.com/assets/975938/8634131/6c9b2546-27ec-11e5-82f3-7f7c788b02b2.png">

**Comment by MengTo** [comment]
So for the detail screen, I'd rather have this action screen.
![menu](https://cloud.githubusercontent.com/assets/1065452/8634202/afe5c09c-27bd-11e5-91fb-83d7ffb77898.png)

**Comment by schneiderandre** [comment]
This is the Version we came up with after our Slack conversation.
![pasted_image_at_2015_07_11_11_39_am_360](https://cloud.githubusercontent.com/assets/975938/8634846/0d142d20-280a-11e5-877c-136e2a0fc889.png)

**Comment by MengTo** [comment]
Looks great!

**Comment by schneiderandre** [comment]
This version is now implemented and tested on the device.

![screen recording 2015-08-03 at 04 17 nachm](https://cloud.githubusercontent.com/assets/975938/9039514/40ea5fe4-39fc-11e5-8de9-7ddd18cea7a8.gif)

After I merge #112, you could submit the App to the Store :smile: .
